// <auto-generated />
using System;
using GuessBook.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuessBook.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200516110953_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuessBook.EF.Entities.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasColumnName("icon")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte?>("Inx")
                        .HasColumnName("inx")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("ParentId")
                        .HasColumnName("parent_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("GuessBook.EF.Entities.Lang", b =>
                {
                    b.Property<byte>("No")
                        .HasColumnName("no")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("No");

                    b.ToTable("lang");
                });

            modelBuilder.Entity("GuessBook.EF.Entities.MemberAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AnswerDigit")
                        .HasColumnName("answer_digit")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("CodeDate")
                        .HasColumnName("code_date")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("MemberId")
                        .HasColumnName("member_id")
                        .HasColumnType("int");

                    b.Property<string>("OptionIds")
                        .HasColumnName("option_ids")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("QuestionId")
                        .HasColumnName("question_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("member_answer");
                });

            modelBuilder.Entity("GuessBook.EF.Entities.Memberipdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CodeDate")
                        .HasColumnName("code_date")
                        .HasColumnType("datetime");

                    b.Property<string>("Ip")
                        .HasColumnName("ip")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Memberid")
                        .HasColumnName("memberid")
                        .HasColumnType("int");

                    b.Property<byte?>("Status")
                        .HasColumnName("status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("memberipdate");
                });

            modelBuilder.Entity("GuessBook.EF.Entities.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivateCode")
                        .HasColumnName("activate_code")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CodeDate")
                        .HasColumnName("code_date")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("Pwd")
                        .HasColumnName("pwd")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("members");
                });

            modelBuilder.Entity("GuessBook.EF.Entities.Options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Photo")
                        .HasColumnName("photo")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("PhotoAlt")
                        .HasColumnName("photo_alt")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("PhotoName")
                        .HasColumnName("photo_name")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("QuestionId")
                        .HasColumnName("question_id")
                        .HasColumnType("int");

                    b.Property<byte?>("Seq")
                        .HasColumnName("seq")
                        .HasColumnType("tinyint")
                        .HasComment("soru index");

                    b.Property<string>("Text")
                        .HasColumnName("text")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("options");
                });

            modelBuilder.Entity("GuessBook.EF.Entities.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<string>("Cat1Parents")
                        .HasColumnName("cat1_parents")
                        .HasColumnType("nchar(100)")
                        .IsFixedLength(true)
                        .HasMaxLength(100);

                    b.Property<byte?>("CategoryId")
                        .HasColumnName("category_id")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnName("end_time")
                        .HasColumnType("smalldatetime")
                        .HasComment("sorunun bitişi (o tarihten sonra gösterilmeyecek)");

                    b.Property<double?>("IncrementSelect")
                        .HasColumnName("increment_select")
                        .HasColumnType("float");

                    b.Property<double?>("MaxSelect")
                        .HasColumnName("max_select")
                        .HasColumnType("float");

                    b.Property<double?>("MinSelect")
                        .HasColumnName("min_select")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("PhotoUrl")
                        .HasColumnName("photoUrl")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<byte?>("QType")
                        .HasColumnName("q_type")
                        .HasColumnType("tinyint")
                        .HasComment("(Soru tipi) 1=Çoktan seçmeli fotolu, 2= Çoktan seçmeli yazı ile, 3= Çoktan çok seçmeli fotograflı, 4=Çoktan çok seçmeli yazılı, 5=Çoktan sıralı seçmeli fotograflı, 6=Çoktan sıralı seçmeli yazılı, 7=Sayılı");

                    b.Property<byte?>("QTypeMax")
                        .HasColumnName("q_type_max")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("QTypeMin")
                        .HasColumnName("q_type_min")
                        .HasColumnType("tinyint");

                    b.Property<string>("Qlink")
                        .HasColumnName("qlink")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<double?>("Score")
                        .HasColumnName("score")
                        .HasColumnType("float");

                    b.Property<byte?>("SponsorIndex")
                        .HasColumnName("sponsor_index")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnName("start_time")
                        .HasColumnType("smalldatetime")
                        .HasComment("sorunun başlangıcı (o tarihten sonra gösterime girecek)");

                    b.Property<string>("Text")
                        .HasColumnName("text")
                        .HasColumnType("varchar(1250)")
                        .HasMaxLength(1250)
                        .IsUnicode(false);

                    b.Property<int?>("TotalAnswer")
                        .HasColumnName("total_answer")
                        .HasColumnType("int")
                        .HasComment("admin girişi yok");

                    b.HasKey("Id");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("GuessBook.EF.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnName("active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("PermGroupId")
                        .HasColumnName("perm_group_id")
                        .HasColumnType("int");

                    b.Property<string>("Pwd")
                        .HasColumnName("pwd")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
